name: Build Rust Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        submodules: recursive # This fetches the submodules

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install build dependencies
      run: sudo apt-get install -y mingw-w64

    - name: Build the project
      env:
        CARGO_INCREMENTAL: 1
      run: cargo build --release --target x86_64-pc-windows-gnu --verbose -j$(nproc) -C opt-level=z

    - name: Upload the executable
      uses: actions/upload-artifact@v3
      with:
        name: player-count-discord-bot
        path: target/x86_64-pc-windows-gnu/release/player-count-discord-bot.exe
